commands = [
  { character_stats = true },
  { cycle_speed = [0.5, 1.0, 2.0, 5.0], hotkey = "8" },
  { flag = "inf_stamina", hotkey = "2" },
  { flag = "inf_consumables", hotkey = "4" },
  { flag = "no_death", hotkey = "6" },
  { flag = "gravity", hotkey = "f2" },
  { flag = "collision", hotkey = "f3" },
]

[settings]
log_level = "DEBUG"
display = "0"
hide = "rshift+0"
show_console = true
indicators = [
  { indicator = "game_version", enabled = true },
  { indicator = "igt", enabled = true },
  { indicator = "position", enabled = false },
  { indicator = "position_change", enabled = false },
  { indicator = "animation", enabled = false },
  { indicator = "fps", enabled = false },
  { indicator = "framecount", enabled = false },
  { indicator = "imgui_debug", enabled = false }
]
