[package]
name = "xtask"
edition = "2021"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"


serde_json.workspace = true
practice-tool-tasks.workspace = true
