// **********************************
// *** AUTOGENERATED, DO NOT EDIT ***
// **********************************
pub struct BaseAddresses {
    pub game_data_man: usize,
    pub world_chr_man: usize,
    pub menu_man: usize,
    pub chr_class_warp: usize,
    pub event_flag_man: usize,
    pub cam_man: usize,
    pub chr_follow_cam: usize,
    pub graphics_data: usize,
    pub ai_timer: usize,
    pub chr_dbg: usize,
    pub group_mask: usize,
    pub get_event_flag_fn: usize,
    pub set_event_flag_fn: usize,
    pub bonfire_warp_fn: usize,
    pub item_get_fn: usize,
}

impl BaseAddresses {
    pub fn with_module_base_addr(self, base: usize) -> BaseAddresses {
        BaseAddresses {
            game_data_man: self.game_data_man + base,
            world_chr_man: self.world_chr_man + base,
            menu_man: self.menu_man + base,
            chr_class_warp: self.chr_class_warp + base,
            event_flag_man: self.event_flag_man + base,
            cam_man: self.cam_man + base,
            chr_follow_cam: self.chr_follow_cam + base,
            graphics_data: self.graphics_data + base,
            ai_timer: self.ai_timer + base,
            chr_dbg: self.chr_dbg + base,
            group_mask: self.group_mask + base,
            get_event_flag_fn: self.get_event_flag_fn + base,
            set_event_flag_fn: self.set_event_flag_fn + base,
            bonfire_warp_fn: self.bonfire_warp_fn + base,
            item_get_fn: self.item_get_fn + base,
        }
    }
}

impl std::fmt::Debug for BaseAddresses {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("BaseAddresses")
            .field("game_data_man", &format_args!("{:#x}", self.game_data_man))
            .field("world_chr_man", &format_args!("{:#x}", self.world_chr_man))
            .field("menu_man", &format_args!("{:#x}", self.menu_man))
            .field("chr_class_warp", &format_args!("{:#x}", self.chr_class_warp))
            .field("event_flag_man", &format_args!("{:#x}", self.event_flag_man))
            .field("cam_man", &format_args!("{:#x}", self.cam_man))
            .field("chr_follow_cam", &format_args!("{:#x}", self.chr_follow_cam))
            .field("graphics_data", &format_args!("{:#x}", self.graphics_data))
            .field("ai_timer", &format_args!("{:#x}", self.ai_timer))
            .field("chr_dbg", &format_args!("{:#x}", self.chr_dbg))
            .field("group_mask", &format_args!("{:#x}", self.group_mask))
            .field("get_event_flag_fn", &format_args!("{:#x}", self.get_event_flag_fn))
            .field("set_event_flag_fn", &format_args!("{:#x}", self.set_event_flag_fn))
            .field("bonfire_warp_fn", &format_args!("{:#x}", self.bonfire_warp_fn))
            .field("item_get_fn", &format_args!("{:#x}", self.item_get_fn))
            .finish()
    }
}

#[derive(Clone, Copy)]
pub enum Version {
    V1_03_1,
}

impl TryFrom<(u32, u32, u32)> for Version {
    type Error = ();

    fn try_from(v: (u32, u32, u32)) -> Result<Self, ()> {
        match v {
            (1, 3, 1) => Ok(Version::V1_03_1),
            (maj, min, patch) => {
                log::error!("Unrecognized version {maj}.{min:02}.{patch}");
                Err(())
            },
        }
    }
}

impl From<Version> for (u32, u32, u32) {
    fn from(v: Version) -> Self {
        match v {
            Version::V1_03_1 => (1, 3, 1),
        }
    }
}

impl From<Version> for BaseAddresses {
    fn from(v: Version) -> Self {
        match v {
            Version::V1_03_1 => BASE_ADDRESSES_1_03_1,
        }
    }
}

pub const BASE_ADDRESSES_1_03_1: BaseAddresses = BaseAddresses {
    game_data_man: 0x1c8a530,
    world_chr_man: 0x1c77e50,
    menu_man: 0x1c88d98,
    chr_class_warp: 0x1c74e08,
    event_flag_man: 0x1c7c5f0,
    cam_man: 0x1c6e188,
    chr_follow_cam: 0x1c7a488,
    graphics_data: 0x1b68ec8,
    ai_timer: 0x1c823a0,
    chr_dbg: 0x1c77e59,
    group_mask: 0x1a2aea0,
    get_event_flag_fn: 0x4f23d0,
    set_event_flag_fn: 0x4f22b0,
    bonfire_warp_fn: 0x4867e0,
    item_get_fn: 0x7479e0,
};
